include ../config.mk

# C source code files
C_FILES := src/credadd.c \
           src/credarr.c \
           src/credfbac.c \
           src/credfbid.c \
           src/credfbtk.c \
           src/credfrea.c \
           src/credfree.c \
           src/credidde.c \
           src/crediden.c \
           src/credidin.c \
           src/credidue.c \
           src/credidup.c \
           src/credinit.c \
           src/credkey.c \
           src/credlin.c \
           src/crednew.c \
           src/credtokl.c \
           src/credtokg.c \
           src/credtest.c

# Assembler source files
A_FILES :=

include ../rules.mk
