/* HTTPD.C
** HTTP Server
*/
/* Build stamp.  Generated by mbt at every build: MBT_VERSION from the project
** version, MBT_COMMIT from `git rev-parse --short HEAD` (with "-dirty"
** appended when a TRACKED file differs from HEAD, and "unknown" outside a git
** checkout), MBT_COMMIT_DIRTY as the matching 0/1 flag.  Included here rather
** than in httpd.h so a new commit restamps the banner without rebuilding every
** object (mbt#59). */
#include <buildstamp.h>

#include "httpd.h"
#include "httpdmsg.h"               /* operator message catalog         */
#include "httpracf.h"               /* HTTP_RACF_NOTPROT (res_probe)    */
#include "clibgrt.h"
#include "clibsock.h"
#include "clibver.h"                /* libc370_version()                */
#include "clibauth.h"               /* __autask/__austep/__uatask/__uastep */

static int socket_thread(void *arg1, void *arg2);
static int worker_thread(void *udata, CTHDWORK *work);

unsigned __stklen = 64*1024;

int main(int argc, char **argv);

#if 0
static void
close_stale_port(int port)
{
	int					rc;
	int					i;
    int                 addrlen;
    struct sockaddr     addr;
    struct sockaddr_in  serv_addr;

	for(i = 1; i < FD_SETSIZE; i++) {
		addrlen = sizeof(addr);
		rc = getsockname(i, &addr, &addrlen);
		if (rc==0) {
			struct sockaddr_in *in = (struct sockaddr_in*)&addr;
			if (in->sin_port == port) {
				wtof(MSG_STALE_SOCKET, i, in->sin_port);
				closesocket(i);
				sleep(2);	/* give the underlying host a chance to cleanup the socket */
				break;
			}
		}
	}
}
#endif

/* The security environment the STC started under -- the STC/STCGROUP account
** RAKF hands out -- is retained by stc_identity() rather than released, so
** that shutdown can put it back before it gives APF authorization up.  It
** lives in the HTTPD control block as httpd->stc_prev_acee: NULL until the
** switch succeeds, which is what makes the restore a no-op on every path that
** never got that far.
**
** It was a file-scope static here until #197.  That is module storage, and a
** module fetched from an APF-authorized or LNKLST library lands in key-0
** storage, so the key-8 store in stc_identity_restore() -- the one outside the
** __super() window -- abended S0C4 on every P HTTPD.  main() memsets the block
** before any path can reach the restore, so the NULL it relies on is
** established exactly as reliably as the static's initializer was. */

/* Replace the default STC security environment with a dedicated, low
** privilege identity.  Called once, from initialize(), before anything opens
** a data set.  See the block comment at the call site for why this exists.
**
** The new ACEE is deliberately not freed: it becomes the address space's
** resting identity for the life of the server, and RTM releases it with the
** address space. */
static void
stc_identity(HTTPD *httpd, const char *user, const char *group)
{
	unsigned char	savekey;
	ACEE			*old_acee;
	ACEE			*new_acee;
	int				racf_rc	= 0;

	if (__super(PSWKEY0, &savekey)) {
		wtof(MSG_STCID_NOKEY);
		return;
	}

	/* The inherited environment is RETAINED, not released.
	**
	** Releasing it would be tidier but breaks shutdown.  HTTPD uses SVC 244 to
	** acquire APF authorization at start and to release it at end (__uatask()).
	** The acquire runs before this function -- RACINIT needs key 0, which needs
	** APF, so that order is forced -- and is covered by the STC account.  The
	** release at P HTTPD would run as the new identity, which has no
	** FACILITY SVC244 profile, and RAKF logs RAKF0005/RAKF000A on every single
	** stop.  stc_identity_restore() puts this ACEE back first, so the SVC 244
	** at the end runs under the same account that took the authorization out.
	**
	** Order also matters within this function, and the obvious order is wrong.
	** Releasing the inherited environment FIRST would leave nothing to fall
	** back on when the logon fails: racf_logout() does not merely free the
	** block, it __cas()es ASXBSENV to zero when the field still points at what
	** it deleted (libc370 raclgout.c does it by hand because RAKF leaves the
	** dead pointer).  A failed logon would then leave the address space with NO
	** resting identity at all -- not what HTTPD004W promises, and worse than the
	** privileged identity #177 set out to replace.  So: log on, then install. */
	old_acee = racf_get_acee();

	new_acee = racf_login(user, NULL, group, &racf_rc);
	if (new_acee) {
		racf_set_acee(new_acee);
		httpd->stc_prev_acee = old_acee;    /* for stc_identity_restore() */
		wtof(MSG_STCID_SET, user, group);
	}
	else {
		wtof(MSG_STCID_FAILED, user, group, racf_rc);
	}

	__prob(savekey, NULL);
}

/* Put the STC account back, immediately before APF authorization is released.
**
** __uatask() issues SVC 244, which RAKF gates on FACILITY SVC244.  The task
** took the authorization out under the STC account and must give it back under
** the same one, or every P HTTPD ends with RAKF0005/RAKF000A -- harmless, since
** the address space is ending anyway, but a permission failure logged on the
** healthy path teaches operators to ignore RAKF messages.
**
** Note this deliberately overwrites whatever ASXBSENV happens to hold, which by
** shutdown is often a CLIENT's ACEE rather than HTTPD/USER (measured: RAKF's
** RACINIT ENVIR=CREATE appears to plant the ACEE it creates, so every logon
** displaces the server identity -- see issue #176).  Restoring unconditionally
** is right precisely because the field cannot be trusted to still hold ours.
**
** racf_set_acee() does its own supervisor/key switching, so no __super() here.
** It does need APF, which is why this runs BEFORE the release, not after.
**
** The saved ACEE lives in the HTTPD control block rather than in a module
** static (#197): main()'s HTTPD is automatic storage and therefore key 8, so
** the clearing store below is legal whatever key the module itself is in. */
static void
stc_identity_restore(HTTPD *httpd)
{
	if (!httpd->stc_prev_acee) return;

	racf_set_acee(httpd->stc_prev_acee);
	httpd->stc_prev_acee = NULL;
}

/* res_probe() - say once, at start, that a RES= route names a resource no
** profile covers.
**
** Stage 2 of auth_gate() permits every request to such a route: SAF answers
** rc 4 ("resource not protected"), httpracf() counts that as allowed, and
** #136 settled deliberately on keeping it that way.  But rc 4 is also exactly
** what a typo in the class or in the resource name looks like, and the one
** keyword whose whole job is authorization should not fail quietly in the
** permissive direction (#137).  The decision itself is unchanged here -- this
** only makes the misconfiguration visible while it can still be fixed.
**
** DEBUG 1 already traces the same condition (httpxauth.c), but per request and
** only for someone who knew to look.  This line is unconditional and lands in
** the job log and the Master Trace Table.
**
** The probe runs under the server's own resting identity -- HTTPD/USER after
** stc_identity(), since acee == NULL takes RACHECK's ASXBSENV fallback -- and
** not under a client's.  That is enough because it asks only whether a profile
** EXISTS: measured against RAKF, an uncovered resource answers 4 whoever asks,
** and the identity moves the answer only between 0 and 8, both of which mean a
** profile is there.
**
** All three arms were measured in one start on mvsdev, with the server running
** as HTTPD/USER: FACILITY:HTTPD.NOSUCH (no profile at all) warned, while
** FACILITY:LIBC370.TSTRACMX.ALLOW (group USER holds READ, so rc 0) and
** FACILITY:LIBC370.TSTRACMX.DENY (defined, nobody permitted, so rc 8) both
** stayed silent.  The second of those is the one worth keeping: it is what
** shows a REFUSAL is not mistaken for a missing profile, which is the whole
** claim this function rests on.  Both profiles exist on that system as RACHECK
** fixtures for libc370's tstracmx, listed in SYS1.SECURE.CNTL(PROFILES).
**
** That is a RAKF property and not a SAF one: under RACF
** with PROTECTALL the same resource answers 8 for an ordinary user and 0 for a
** SPECIAL one (see the RACHECK return codes in libc370 racauth.c), and MVS
** 3.8j with no security product at all answers 0.  Only rc 4 warns, so on
** either of those this stays silent rather than warning falsely.
**
** AUTH=NONE routes are skipped: auth_gate() never reaches stage 2 for them and
** HTTPD414W has already said the RES= is ignored.  parse_kv_tail() leaves
** resclass set on such a route rather than clearing it, so this test is live
** code, not a defensive one.
**
** Cost is one RACHECK per RES= route, once -- and it audits nothing, now that
** libc370#63 has racf_auth() setting LOG=NONE instead of DSTYPE=V.
*/
static void
res_probe(HTTPD *httpd)
{
	unsigned	count;
	unsigned	n;

	if (!httpd->route) return;

	count = array_count(&httpd->route);
	for (n = 0; n < count; n++) {
		HTTPROUTE *route = httpd->route[n];

		if (!route->resclass || !route->resname) continue;
		if (route->auth == HTTP_AUTH_NONE) continue;

		if (racf_auth(NULL, route->resclass, route->resname, route->resattr)
		    == HTTP_RACF_NOTPROT) {
			wtof(MSG_RES_NO_PROFILE,
			     route->resclass, route->resname, route->path);
		}
	}
}

/* initialize() - returns the step return code: 0 when the server came up, 8
** when it refused to.  It used to be void, which is how a Parmlib error the
** server explicitly refuses to start on still ended the step CC 0000 (#226):
** http_config() returned 8, initialize() acted on it, and the value had
** nowhere to go.  main() then inferred the failure from !httpd->listen, and an
** inference carries no severity -- so in JES a refused configuration was
** indistinguishable from a clean P HTTPD, for $DJ, for an automation rule
** keyed on COND CODE, and for anything that restarts a failed STC.
**
** Kept in its own variable rather than reusing rc, which is written again
** further down by cthread_post() and cred_init(); returning rc would report
** whichever of those ran last. */
static int
initialize(int argc, char **argv)
{
    int                 initrc  = 0;    /* step return code -- see above */
    CLIBGRT             *grt        = __grtget();
    CLIBPPA             *ppa        = __ppaget();
    HTTPD               *httpd      = grt->grtapp1;
    unsigned            *psa        = (unsigned *)0;
    unsigned            *ascb       = (unsigned *)psa[0x224/4]; /* PSAAOLD  */
    unsigned            asid        = ((ascb[0x24/4]) >> 16);   /* ASCBASID */
    int                 rc;
    int					i;
    CTHDTASK            *task;
    const char 			*config		= NULL;
    const char			*stcuser	= HTTPD_STC_USER;
    const char			*stcgroup	= HTTPD_STC_GROUP;

    /* if something goes all wrong, capture it! */
    abendrpt(ESTAE_CREATE, DUMP_DEFAULT);

	/* look for "CONFIG=", "STCUSER=" and "STCGROUP=" parms.
	**
	** The identity keywords are read from the JCL PARM rather than from the
	** Parmlib on purpose: the logon below has to happen BEFORE http_config(),
	** which opens the Parmlib member and initializes UFS, and those are
	** exactly the file accesses that should no longer run under STC/STCGROUP.
	** Reading them from the member being opened would be circular. */
	for(i=0; i < argc; i++) {
		if (memcmp(argv[i], "CONFIG=", 7)==0) {
			config = &argv[i][7];
			while(*config=='=' || isspace((unsigned char)*config)) config++;
			if (!*config) config = "CONFIG";
		}
		else if (memcmp(argv[i], "STCUSER=", 8)==0) {
			stcuser = &argv[i][8];
			while(*stcuser=='=' || isspace((unsigned char)*stcuser)) stcuser++;
			if (!*stcuser) stcuser = HTTPD_STC_USER;
		}
		else if (memcmp(argv[i], "STCGROUP=", 9)==0) {
			stcgroup = &argv[i][9];
			while(*stcgroup=='=' || isspace((unsigned char)*stcgroup)) stcgroup++;
			if (!*stcgroup) stcgroup = HTTPD_STC_GROUP;
		}
	}

	/* STC identity switch: RACINIT ENVIR=CREATE for the configured userid.
	**
	** RAKF has no started-procedures table: its RACINIT path uses the started
	** procedure name only to decide THAT the caller is an STC, never WHICH
	** one, and assigns one hardcoded account -- STC/STCGROUP.  On a stock RAKF
	** profile set STCGROUP holds ALTER on every data set on the system, so the
	** server's resting identity, the one every RACF decision falls back to when
	** the caller passes no ACEE, is the most privileged one there is.  Any CGI
	** that does not establish an ACEE of its own inherits it (issue #177).
	**
	** racf_login() with pass == NULL bypasses password checking, so nothing has
	** to be stored anywhere; the STC is already APF authorized by this point.
	**
	** A failure warns and continues rather than refusing to start: #177 left
	** the policy open, and refusing turns a profile typo into an outage, while
	** continuing only leaves the identity where it already was.  Both paths say
	** so loudly -- what must not happen is a silent fallback. */
	stc_identity(httpd, stcuser, stcgroup);

    /* The block itself was zeroed by main() before any of this ran -- it has
       to be, because stc_identity() above already stores into it and because
       the early-failure paths in main() reach stc_identity_restore() without
       ever calling us (#197). */
    strcpy(httpd->eye, HTTPD_EYE);
    httpd->flag |= HTTPD_FLAG_INIT;
    sprintf(httpd->rname, "HTTPD.%04X", asid);

    /* lock the httpd while we're making changes and creating threads */
    lock(httpd,0);

    /* httpd <--> httpx */
    httpd->httpx = httpx;
    
    /* set the server up time */
    httpd->uptime = time64(NULL);

    /* Server version.  MBT_VERSION rather than a -DVERSION on the command
       line: as a header it is a real prerequisite via -MMD, so a version or
       commit change recompiles this TU instead of leaving it stamped with the
       previous value.  Kept in its original case -- it is a value, and the
       WTO paths upper case their own copy (httpdmsg.h rule 3). */
    httpd->version	= MBT_VERSION;

	/* Get configuration from member/dataset/NULL */
	rc = http_config(httpd, config);
	if (rc) {
		/* The member is named by HTTPD022I above, and the specific failure by
		   the message right before this one -- printing the CONFIG= parm here
		   only ever produced "(null)", since it is not what gets read (#166). */
		wtof(MSG_CFG_ERRORS);
		if (httpd->listen) {
			closesocket(httpd->listen);
			httpd->listen = 0;
		}
		initrc = rc;                    /* 8 from http_config() (#226) */
		goto quit;
	}

	/* SMF configured but inactive is worth a line unasked: records are being
	** produced for a writer that is not there.  The healthy case is not --
	** it is one of the values F HTTPD,D CONFIG reports on demand (#184). */
	if (httpd->smf_level > SMF_LEVEL_NONE && !smf_active()) {
		wtof(MSG_SMF_INACTIVE, (int)httpd->smf_type);
	}

	/* Same shape, same reason: a RES= route whose resource has no profile is
	** configured for an authorization that cannot happen.  The routes exist
	** only once http_config() has parsed them, and there is no way to reload
	** the Parmlib, so this is the one point that needs it (#137). */
	res_probe(httpd);

    /* create socket thread */
    httpd->socket_thread = cthread_create_ex(socket_thread,
        httpd, httpx, 32*1024);
    if (!httpd->socket_thread) {
        wtof(MSG_NO_SOCKET_THREAD);
        closesocket(httpd->listen);
        httpd->listen = 0;
        initrc = 8;                     /* did not come up either (#226) */
        goto quit;
    }

    httpd->flag |= HTTPD_FLAG_LISTENER;

    /* update the main() thread information */
    task = cthread_self();
    if (task) {
        httpd->self = task;
        task->func = main;
        task->arg1 = (void*)argc;
        task->arg2 = argv;
        task->stacksize = ppa->ppastkln;
    }

	/* check configuration max and min task values */
    if (!(httpd->cfg_maxtask)) httpd->cfg_maxtask = 9;
    if (!(httpd->cfg_mintask)) httpd->cfg_mintask = 3;
    if (httpd->cfg_mintask > httpd->cfg_maxtask) {
		httpd->cfg_maxtask = httpd->cfg_mintask;
	}

    /* create 1 dispatcher and max 9 worker threads (576K total storage stack) */
    /* Note: the thread manager will only start 3 threads initially */
    httpd->mgr = cthread_manager_init(httpd->cfg_maxtask, worker_thread, httpd, 64*1024);
    if (!httpd->mgr) {
        /* gripe and continue -- deliberately does NOT set initrc.  Whether a
           server with no worker pool should start at all is a separate
           question from what code it ends with, and this path has always
           chosen to come up; #226 only made the refusals honest. */
        wtof(MSG_NO_WORKERS);
    }

	/* set the min task for the thread manager */
    if (httpd->mgr) {
		CTHDMGR *mgr = httpd->mgr;

        lock(mgr,1);

		mgr->mintask = httpd->cfg_mintask;
		if (httpd->cfg_mintask > mgr->maxtask) mgr->maxtask = httpd->cfg_mintask;

		/* wake up the thread manager thread */
		rc = cthread_post(&mgr->wait, CTHDMGR_POST_DATA);

        unlock(mgr,1);
    }
    
    /* Initialize CGI context pointers array */
    i = (httpd->cfg_cgictx + 1) * sizeof(void *);
    httpd->cgictx = (void **) calloc(1, (size_t)i);

quit:
	/* Initialize our credential key.

	   The salt used to be the HTTPD block on its own.  That is not a secret:
	   of its 392 bytes roughly half are literal text (eye catcher, docroot,
	   codepage), the rest is Parmlib configuration plus counters that are all
	   zero at this point, and the only varying part is a handful of GETMAIN
	   addresses.  MVS 3.8j has no address space layout randomisation, so for
	   the same load module, region size and Parmlib those addresses reproduce
	   and the key came out identical on every start -- derivable by anyone
	   holding the load module and the Parmlib (#188).

	   Mixing STCK and this address space's own control block addresses through
	   SHA-256 makes the key differ per start.  That matters twice: the CREDID
	   passwords encrypted with it stop being decryptable from a dump by someone
	   who can rebuild the server, and the key becomes usable as the secret that
	   makes credtok_rand()'s output unpredictable.

	   Note this invalidates any credential built by a previous instance: the
	   encrypted CREDID is the lookup key in cred_find_by_id() and it is
	   ciphertext.  Harmless, because the store dies with the address space --
	   but it would matter if credentials were ever persisted. */
	{
		SHA256_CTX          ctx;
		unsigned char       salt[32];
		unsigned long long  tod;
		unsigned            *tcb  = (unsigned *)psa[0x21C/4];  /* PSATOLD */
		void                *self = httpd;

		__asm__("STCK\t0(%0)" : : "r" (&tod));

		sha256_init(&ctx);
		sha256_update(&ctx, (unsigned char *)&tod,  sizeof(tod));
		sha256_update(&ctx, (unsigned char *)httpd, sizeof(HTTPD));
		sha256_update(&ctx, (unsigned char *)&self, sizeof(self));
		sha256_update(&ctx, (unsigned char *)&ascb, sizeof(ascb));
		sha256_update(&ctx, (unsigned char *)&tcb,  sizeof(tcb));
		sha256_final(&ctx, salt);

		rc = cred_init(salt, sizeof(salt));

		memset(salt, 0, sizeof(salt));
	}
	/* Same classification as the worker pool above: HTTPD047E says logins are
	   dead, but the server has always come up anyway, so this does not set
	   initrc either.  Note rc is cred_init()'s from here on -- initrc is what
	   this function returns. */
	if (rc) {
		wtof(MSG_CREDKEY_FAILED, rc);
	}

	/* Cache the blowfish key pointer in the HTTPD block so CGI-context code
	   (http_get_password) can reach it without credkey()/__wsaget(), which
	   only read the key from httpd's own GRT.  cred_init() runs here in that
	   GRT, so credkey() is valid; the key bytes live at a stable WSA address
	   readable across the shared address space, so caching the pointer (no
	   copy) is enough for a CGI running under its own GRT (issue #111). */
	httpd->credkey = credkey();

	/* Likewise cache the credential array pointer so http_logout() can reach
	   httpd's real store from a CGI's GRT.  cred_array() is GRT-relative too,
	   so a CGI calling it sees an empty/foreign array and logout invalidates
	   nothing; caching httpd's array pointer here (in httpd's GRT) fixes it
	   (issue #113, same class as #111). */
	httpd->credarr = cred_array();

    /* unlock the httpd */
    unlock(httpd,0);

    /* remove ESTAE */
    abendrpt(ESTAE_DELETE, DUMP_DEFAULT);

    http_exit("initialize()\n");
    return initrc;
}

#if 0
static int
report_abend(unsigned abcode)
{
    int     rc;

    http_enter("report_abend()\n");

    abcode = (unsigned) rc;
    if (abcode > 4095) {
        /* system abend */
        wtof(MSG_ABEND_S, abcode >> 12);
        rc = 12;
    }
    else {
        /* user abend */
        wtof(MSG_ABEND_U, abcode);
        rc = 12;
    }

    http_exit("report_abend()\n");
    return rc;
}
#endif // 0

static void
close_fd_set(void)
{
    CLIBGRT *grt    = __grtget();

    http_enter("close_fd_set()\n");
    if (grt->grtsock) {
        unsigned count  = array_count(&grt->grtsock);
        while(count > 0) {
            count--;
            CLIBSOCK *s = grt->grtsock[count];
            if (!s) continue;
            if (s->socket >= 0) {
                closesocket(s->socket);
            }
        }
    }
    http_exit("close_fd_set()\n");
}

static void
terminate(void)
{
    CLIBGRT *grt        = __grtget();
    HTTPD   *httpd      = grt->grtapp1;
    HTTPC   *httpc;
    int     i;
    unsigned count;
    unsigned n;

    http_enter("terminate()\n");

    httpd->flag |= HTTPD_FLAG_QUIESCE;
    httpd->flag |= HTTPD_FLAG_SHUTDOWN;

    if (httpd->socket_thread) {
        CTHDTASK *task = httpd->socket_thread;

        for(i=0; (i < 10) && (!(task->termecb & 0x40000000)); i++) {
            if (i) {
                wtof(MSG_WAIT_SOCKET_THREAD, i);
            }
            /* we need to wait 1 second */
            __asm__("STIMER WAIT,BINTVL==F'100'   1 seconds");
        }

        if(!(task->termecb & 0x40000000)) {
            wtof(MSG_FORCE_DETACH);
        }
        cthread_delete(&httpd->socket_thread);
    }

    /* close the listener socket */
    if (httpd->listen > 0) {
        http_dbgf("closing socket(%d)\n", httpd->listen);
        closesocket(httpd->listen);
        httpd->listen = 0;
    }

    /* terminate the worker threads */
    cthread_manager_term(&httpd->mgr);

    if (httpd->httpc) {
        for(httpc=httpd->httpc[0]; httpc; httpc=httpd->httpc[0]) {
            http_dbgf("closing socket(%d)\n", httpc->socket);
            http_close(httpc);
        }
        array_free(&httpd->httpc);
    }

    /* cleanup the CGI array */
    if (httpd->route) {
        count = array_count(&httpd->route);

        for(n=0; n < count; n++) {
            HTTPROUTE *route = httpd->route[n];
			if (route->pgm) 	free(route->pgm);
			if (route->path) 	free(route->path); 
            free(route);
        }

        array_free(&httpd->route);
    }

    /* free the per-CGI context pointer array (M11); the blocks it points to
       are AS-lifetime __getm storage by design and are not freed here */
    if (httpd->cgictx) {
        free(httpd->cgictx);
        httpd->cgictx = NULL;
    }

    /* httpd->ufs removed — per-client sessions freed in httpclos.c */

    if (httpd->ufssys) {
        ufs_sys_term(&httpd->ufssys);
        httpd->ufssys = NULL;
    }

	wtof(MSG_STATS,
		httpd->total_requests, httpd->total_errors,
		httpd->total_bytes_sent);

    /* just in case we missed something */
    close_fd_set();

    wtof(MSG_SHUTDOWN_DONE);

    http_exit("terminate()\n");
}

static int
build_fd_set(fd_set *read, fd_set *write, fd_set *excp)
{
    CLIBGRT     *grt    = __grtget();
    HTTPD       *httpd  = grt->grtapp1;
    int         maxsock = 0;
    unsigned    count   = array_count(&httpd->httpc);
    unsigned    n;
    HTTPC       *httpc;
#if 0
    http_enter("build_fd_set()\n");
#endif
    if (read && httpd->listen >= 0) {
        memset(read, 0, sizeof(fd_set));
        FD_SET(httpd->listen, read);
        if (httpd->listen > maxsock) maxsock = httpd->listen;
    }
    if (write) {
        memset(write, 0, sizeof(fd_set));
    }
    if (excp) {
        memset(excp, 0, sizeof(fd_set));
    }

    /* httpd->httpc[] is read here without the lock.  That is safe because the
     * array has exactly one writer, and it is this thread -- not because of
     * any NULL in it (#235).
     *
     * Entries reach it only through the accept path below, in the branch taken
     * when httpd->mgr is NULL -- and that is the no-worker fallback alone, not
     * a startup window.  http_config() is already listening well before this
     * thread exists, but initialize() holds lock(httpd,0) from before
     * cthread_create_ex() until after cthread_manager_init(), and every pass
     * of this loop starts in process_clients() -> http_process_clients(),
     * which ENQs that same resource.  lock() is ENQ RET=HAVE (libc370
     * @@enqdeq.c), so another TCB's holder makes it wait, not fail: this
     * thread cannot reach accept() until mgr is set or has failed.  A
     * connection sitting in the backlog at STC start therefore does not slip
     * into this array, and with a worker pool the array stays empty for the
     * life of the server.
     *
     * Which leaves the fallback -- and no manager means no worker threads at
     * all.  The accept below, both walks over the array, and the array_del()
     * in httpclos() then run on this one thread; nothing else exists to race
     * it.  (Workers, when they exist, take their clients from
     * cthread_queue_add() alone and never see this array.  httpd->busy does
     * hold client pointers a worker touches, but nothing walks it to close or
     * free a client -- it is add / delete-this-one / compare-only.)
     *
     * One exception, worth knowing before trusting this: if the socket thread
     * does not post its termination ECB within 10s, terminate() says
     * HTTPD041I, detaches it anyway, and then walks and frees this array from
     * the main thread.  A socket thread still running past that point is a
     * second writer -- and a far wider problem than this array.
     *
     * What stood here claimed array_del() "sets entries to NULL before removal,
     * and we check for NULL below".  It does not: arraydel() shifts every later
     * element left and NULLs only the slot past the new count (libc370
     * @@ardel.c).  The check that argument justified is gone with the
     * single-writer finding; see docs/development.md, "Dynamic arrays: no holes
     * below the count".
     */
    for(n=0; n < count; n++) {
        httpc = httpd->httpc[n];

        if (httpc->socket < 0) continue;   /* no socket? */

        if (httpc->socket > maxsock) maxsock = httpc->socket;
        if (read)   FD_SET(httpc->socket, read);
        if (write)  FD_SET(httpc->socket, write);
        if (excp)   FD_SET(httpc->socket, excp);
    }

    if (maxsock) maxsock++;
#if 0
    http_exit("build_fd_set(), maxsock=%d\n", maxsock);
#endif
    return maxsock;
}

static int
process_clients(fd_set *read, fd_set *write, fd_set *excp)
{
    CLIBGRT     *grt    = __grtget();
    HTTPD       *httpd  = grt->grtapp1;
    int         rc      = http_process_clients();
    int         lockrc;
    unsigned    count;
    unsigned    n;
    HTTPC       *httpc;

    /* process all the http clients (does its own locking) */
    rc = http_process_clients();

    /* get lock so we can cleanup any clients that are closing */
    lockrc = lock(httpd, 0);
    if (lockrc==0) goto httpd_locked;   /* we have the lock */
    if (lockrc==8) goto httpd_locked;   /* we already had the lock */
    wtof(MSG_LOCK_FAILED, __func__);
    goto quit;

httpd_locked:
    /* look for any clients that need to be closed */
    count = array_count(&httpd->httpc);
    for(n=0; n < count; n++) {
        httpc = httpd->httpc[n];

        if (httpc->state==CSTATE_CLOSE) {
            /* we close a single client at a time,
            ** other clients will be closed on next pass.
            */
            http_dbgf("closing client(%u) socket(%d)\n",
                n+1, httpc->socket);
            http_close(httpc);
            break;
        }
    }
    if (lockrc==0) unlock(httpd, 0);

quit:
    return 0;
}

/* NOTE: an earlier version of this probe bisected with malloc() to report the
   largest obtainable block.  It abended the socket thread S878 on its second
   run -- libc370's malloc goes to @@GETM, which issues GETMAIN **RU**
   (unconditional): under storage pressure it abends instead of returning
   NULL.  That is the defect this debugging found, so the probe must never
   allocate; it only reports counts. */

static int
socket_thread(void *arg1, void *arg2)
{
    CLIBGRT     *grt    = __grtget();
    HTTPD       *httpd  = grt->grtapp1;
    unsigned    *psa    = (unsigned *)0;
    unsigned    *tcb    = (unsigned *)psa[0x21C/4]; /* A(TCB) from PSATOLD  */
    CTHDTASK    *task   = cthread_self();
    CTHDMGR     *mgr    = httpd->mgr;
    int         rc;
    int         sock;
    int         len;
    HTTPC       *httpc;
    timeval     wait;
    int         maxsock;
    unsigned    count;
    fd_set      read;
    struct sockaddr_in addr;
    struct sockaddr_in *a = (struct sockaddr_in *)&addr;
    time64_t    last_sweep = time64(NULL);  /* credential reaper throttle (M2) */

    http_enter("socket_thread()\n");

    wtof(MSG_THREAD_START, "SOCKET THREAD", tcb, task, task->stacksize);

    /* if something goes all wrong, capture it! */
    abendrpt(ESTAE_CREATE, DUMP_DEFAULT);

    /* we loop until we're shut down */
    while(task) {
        if (httpd->flag & HTTPD_FLAG_SHUTDOWN) break;

        /* periodically reap idle credentials (M2), throttled to ~60s so the
           select loop's ~1/s wakeups don't sweep every tick */
        {
            time64_t now = time64(NULL);
            if (difftime64(now, last_sweep) >= 60.0) {
                last_sweep = now;
                if (httpd->cfg_session_timeout || httpd->cfg_session_maxage)
                    cred_reap((unsigned)httpd->cfg_session_timeout * 60,
                              (unsigned)httpd->cfg_session_maxage * 60);
            }
        }

        /* process clients */
        if (process_clients(&read, NULL, NULL)) break;

        /* build fd_set for select() */
        maxsock = build_fd_set(&read, NULL, NULL);
        if (!maxsock) {
            wtof(MSG_MAXSOCK_ZERO);
            goto quit;
        }

        /* set the wait interval */
        wait.tv_sec     = 0;
        wait.tv_usec    = 0;

        mgr = httpd->mgr;
        if (mgr) {
            /* we're using worker threads for client processing */
            wait.tv_sec = 1;

            /* if we're quiesced then break out of loop */
            if (httpd->flag & HTTPD_FLAG_QUIESCE) break;
        }
        else {
            /* we're doing client processing from this thread */
            count       = array_count(&httpd->httpc);

            if (count==0) {
                /* no clients, so wait just a little bit */
                wait.tv_sec = 1;

                /* if we're quiesced then break out of loop */
                if (httpd->flag & HTTPD_FLAG_QUIESCE) break;
            }
        }

        /* wait for something to do */
        rc = selectex(maxsock, &read, NULL, NULL, &wait, NULL);
        if (rc<0) {
            if (httpd->flag & HTTPD_FLAG_QUIESCE) continue;     /* checked at top of loop */
            if (httpd->flag & HTTPD_FLAG_SHUTDOWN) continue;    /* checked at top of loop */
            wtof(MSG_SELECT_FAILED, rc, errno);
            goto quit;
        }

        /* if we're quiesced then don't accept new connections */
        if (httpd->flag & HTTPD_FLAG_QUIESCE) continue;

        /* first check for new connections */
        if (FD_ISSET(httpd->listen, &read)) {
            /* new client wants to connect */
            len = sizeof(addr);
            sock = accept(httpd->listen, &addr, &len);
            if (sock<0) {
                /* transient (client reset before accept, EINTR, ...): drop
                   this connection but keep listening.  A real shutdown/quiesce
                   is handled at the top of the loop, so don't kill the
                   listener on a single accept() failure. */
                if (httpd->flag & HTTPD_FLAG_QUIESCE) continue;
                if (httpd->flag & HTTPD_FLAG_SHUTDOWN) continue;
                wtof(MSG_ACCEPT_FAILED, sock, errno);
                http_dbgf("accept() failed, rc=%d, error=%d\n", sock, errno);
                continue;
            }

            http_dbgf("new connection on socket=%d\n", sock);

            len = 1;    /* set non-blocking I/O */
            if (ioctlsocket(sock, FIONBIO, &len)) {
                wtof(MSG_NONBLOCK_FAILED, sock);
                http_dbgf("Unable to set non-blocking I/O for socket %d\n",
                    sock);
            }

            /* we've accepted a connection */
            httpc = calloc(1, sizeof(HTTPC));
            if (!httpc) {
                /* out of memory for this client: close the accepted socket
                   (don't leak the fd) and keep listening -- memory may free
                   up; a persistent OOM still lets QUIESCE/SHUTDOWN exit. */
                wtof(MSG_OUT_OF_MEMORY);
                closesocket(sock);
                continue;
            }
            strcpy(httpc->eye, HTTPC_EYE);
            httpc->httpd  = httpd;
            httpc->socket = sock;
            httpc->addr   = a->sin_addr.s_addr;
            httpc->port   = a->sin_port;
            httpc->state  = CSTATE_IN;
            httpsecs(&httpc->start);
            httpd->active_connections++;

            // SMF session tracking
            {
                time_t now = time(0);
                struct tm *tm = localtime(&now);
                httpc->connect_time = (unsigned)(
                    tm->tm_hour * 360000L
                    + tm->tm_min * 6000L
                    + tm->tm_sec * 100L);
            }
            /* UFS session created lazily by http_get_ufs() */

            mgr = httpd->mgr;
            if (mgr) {
                /* we have a thread manager */
                if (mgr->state == CTHDMGR_STATE_QUIESCE ||
                    mgr->state == CTHDMGR_STATE_STOPPED) {
                    /* manager is not available */
                    http_close(httpc);
                }
                else {
                    /* queue client to thread manager work queue.  A calloc
                       OOM inside cthread_queue_add returns non-zero without
                       queueing -- close the client so its HTTPC + socket don't
                       leak.  (Success returns 0; a QUIESCE/STOPPED race also
                       returns 0 there, but is covered by the state check above
                       -- the narrow remaining window is benign, reclaimed at
                       address-space end.) */
                    if (cthread_queue_add(mgr, httpc)) {
                        http_close(httpc);
                    }
                }
            }
            else {
                /* add new client to array of clients */
                lock(httpd, 0);
                array_add(&httpd->httpc, httpc);
                unlock(httpd, 0);
            }
        } /* if (FD_ISSET(httpd->listen, &read)) */

    } /* while(task) */

quit:
	wtof(MSG_THREAD_STOP, "SOCKET THREAD", tcb, task, task->stacksize);

    abendrpt(ESTAE_DELETE, DUMP_DEFAULT);
    http_exit("socket_thread()\n");
    return 0;
}

/* Drive one client's state machine to completion (or to shutdown).  Split
   out so worker_thread can run it under try() (ESTAE): a core abend anywhere
   in the request pipeline then returns here for cleanup instead of
   percolating past http_close() -- which would otherwise leak the HTTPC, its
   socket, env and UFS handles and leave a stale pointer in httpd->busy (M1). */
static int
serve_client(HTTPC *httpc, CTHDWORK *work)
{
    /* DEBUG #217: this loop had no escape.  http_process_client() may return
       without advancing httpc->state (the busy-exit in httppc.c), and there is
       no wait anywhere in the loop, so the worker then spins on ENQ/DEQ
       forever and is lost to the pool.  Count passes that change nothing and
       break out, loudly, instead of taking the address space down. */
    int     spin    = 0;
    short   last    = httpc->state;

    while (httpc->state != CSTATE_CLOSE) {
        http_process_client(httpc);
        if (work->state == CTHDWORK_STATE_SHUTDOWN) break;

        if (httpc->state == last) {
            /* No progress.  In worker mode this client has exactly one owner
               -- this loop; it came off the work queue and nothing else
               processes it.  So if the no-progress pass was httppc()'s
               busy-exit, the httpd->busy entry is stale by definition (#159:
               left behind by an earlier failure on this worker, or by a freed
               client that occupied the same storage).  Clear it on the FIRST
               such pass and keep serving: the request proceeds normally and
               the wedge never forms.  If the client is NOT in busy, the stall
               has another cause (e.g. http_set_busy() failing on a full
               region) -- nothing to repair here, let the spin guard below end
               it.  The guard stays as the last resort either way. */
            if (spin == 0 && http_is_busy(httpc)) {
                wtof(MSG_STALE_BUSY,
                    httpc, (int)httpc->state, httpc->socket,
                    httpc->request_count);
                http_reset_busy(httpc);
            }
            if (++spin >= 1000) {
                wtof(MSG_SPIN,
                    httpc, (int)httpc->state, httpc->socket,
                    httpc->request_count, work);
                /* The spin means httppc() kept taking its busy-exit without
                   ever reaching http_reset_busy(), so this client is still in
                   httpd->busy -- and http_close() does not clear that array.
                   Drop the entry here, or the freed HTTPC address stays behind
                   and wedges the next client allocated at it. */
                http_reset_busy(httpc);
                httpc->state = CSTATE_CLOSE;
                break;
            }
        }
        else {
            spin = 0;
            last = httpc->state;
        }
    }
    return 0;
}

static int
worker_thread(void *udata, CTHDWORK *work)
{
    unsigned    *psa    = (unsigned *)0;
    unsigned    *tcb    = (unsigned *)psa[0x21C/4]; /* A(TCB) from PSATOLD  */
    CTHDTASK    *task   = cthread_self();
    int         rc      = 0;
    char        *data   = NULL;
    HTTPC       *httpc  = NULL;
    char        name[20];   /* "WORKER(xxxxxx)" for HTTPD060I/061I */

    http_enter("worker_thread()\n");

    /* if something goes all wrong, capture it! */
    abendrpt(ESTAE_CREATE, DUMP_DEFAULT);

    sprintf(name, "WORKER(%06X)", (unsigned)work);
    wtof(MSG_THREAD_START, name, tcb, task, task->stacksize);

    while(task) {
        if (work->state == CTHDWORK_STATE_SHUTDOWN) break;

        rc = cthread_worker_wait(work,&data);
        if (rc == CTHDWORK_POST_SHUTDOWN) break;

        if (rc == CTHDWORK_POST_REQUEST) {
            /* process request */
            httpc = (HTTPC*)data;
            if (httpc && strcmp(httpc->eye, HTTPC_EYE)==0) {
                /* Run the request under ESTAE.  A core abend (not a CGI under
                   __linkds, whose abends are caught there) would otherwise
                   skip http_close() and leak the client; try() catches it so
                   cleanup still runs.  On an abend the pipeline never reached
                   http_reset_busy() (httppc.c:149), so drop the stale busy
                   entry here -- while httpc is still valid, before close frees
                   it.  The normal path already cleared busy, so gate on rc. */
                rc = try(serve_client, httpc, work);
                if (rc) {
                    wtof(MSG_WORKER_ABEND,
                        rc, work, httpc, httpc->socket);
                    http_reset_busy(httpc);
                }
                http_dbgf("closing client(%08X) socket(%d)\n",
                    httpc, httpc->socket);
                http_close(httpc);
            }
            else {
                wtodumpf(data, 16, "%s unknown request", __func__);
            }
        }
        else if (rc == CTHDWORK_POST_TIMER) {
            /* process timer */
        }
    }

	wtof(MSG_THREAD_STOP, name, tcb, task, task->stacksize);

    abendrpt(ESTAE_DELETE, DUMP_DEFAULT);

    http_exit("worker_thread()\n");
    return 0;
}

static unsigned
build_ecblist(COM *com, unsigned **ecblist)
{
    unsigned        pos     = 0;
    unsigned        *ecbp;

    if (com->comecbpt) {
        ecblist[pos++] = com->comecbpt;
    }

    if (pos) {
        ecbp = ecblist[pos-1];
        ecblist[pos-1] = (unsigned*)((unsigned)ecbp | 0x80000000);
    }

    return pos;
}

#include "cde.h"
static CDE *
find_cde(const char *name)
{
    unsigned    *psa    = 0;                        /* low core == PSA      */
    unsigned    *tcb    = (unsigned*)psa[0x21c/4];  /* TCB      == PSATOLD  */
    unsigned    *jstcb  = (unsigned*)tcb[0x7c/4];   /* JSTCB    == TCBJSTCB */
    CDE         *cde    = (CDE*)jstcb[0x2c/4];      /* CDE      == TCBJPQ   */
    int         i;
    char        temp[9] = "        ";

    for(i=0; i < 8 && name[i]; i++) {
        temp[i] = name[i];
    }

    while(cde) {
        if (memcmp(cde->CDNAME, temp, 8)==0) {
            return cde;
            break;
        }
        cde = cde->CDCHAIN;
    }

    return NULL;
}

static int
auth_cde(CDE *cde)
{
    int     rc = 0;

    if (cde) {
        __asm__("MODESET KEY=ZERO,MODE=SUP\n" : : : "0", "1", "14", "15");
        cde->CDATTR2 |= (CDSYSLIB | CDAUTH);
        __asm__("MODESET KEY=NZERO,MODE=PROB" : : : "0", "1", "14", "15");
    }

    return rc;
}

static int
auth_name(const char *name)
{
    int     rc = 0;
    CDE     *cde = find_cde(name);

    if (cde) {
        /* wtodumpf(cde, sizeof(CDE), "%s %s CDE before auth_cde()", __func__, name); */
        rc = auth_cde(cde);
        /* wtodumpf(cde, sizeof(CDE), "%s %s CDE after auth_cde()", __func__, name); */
    }
    else {
        /* wtof("%s %s CDE was not found", __func__, name); */
        rc = 4;
    }

    return rc;
}

static int
identify_cthread(void)
{
    int     rc = 0;

    /* CTHREAD does not already exist, identify it now */
    /* wtof("%s preparing to IDENTIFY CTHREAD", __func__); */

    __asm__("L     1,=V(CTHREAD)    A(thread driver routine)\n\t"
            "LA    0,=CL8'CTHREAD'\n\t"
            "IDENTIFY EPLOC=(0),ENTRY=(1)\n\t"
            "ST    15,0(,%0)\n" : : "r" (&rc): "0", "1", "14", "15");
    __asm__("\n*\n");

    /* wtof("%s IDENTIFY CTHREAD rc=%d", __func__, rc); */

    rc = auth_name("CTHREAD");

    return rc;
}

static int auth_setup(const char *name)
{
    int     rc = 0;

    return rc;
}

static int unauth_setup(const char *name)
{
    int         rc      = 0;
    CLIBCRT     *crt    = __crtget();   /* A(CLIBCRT)               */

    /* this task is not currently APF authorized */
    rc = __autask();    /* APF authorize this task  */
    /* wtof("%s __autask() rc=%d", __func__, rc); */
    if (rc==0) {
        if (crt->crtauth & CRTAUTH_ON) {
            /* Silent on the healthy path (UFSD/FTPD do the same): that APF was
            ** obtained is only interesting when it FAILS, and HTTPD012E covers
            ** that. */
            /* we want the STEPLIB APF authorized as well */
            rc = __austep();    /* APF authorize the STEPLIB */
            if (rc==0) {
                if (crt->crtauth & CRTAUTH_STEPLIB) {
                    rc = auth_name(name);
                    /* wtof("%s auth_name(%s) rc=%d", __func__, name, rc); */
                    rc = identify_cthread();
                    /* wtof("%s identify_cthread() rc=%d", __func__, rc); */
                }
            }
        }
        else {
            rc = auth_name(name);
            /* wtof("%s auth_name(%s) rc=%d", __func__, name, rc); */
            rc = identify_cthread();
            /* wtof("%s identify_cthread() rc=%d", __func__, rc); */
        }
    }
    else {
        wtof(MSG_APF_FAILED, name);
    }

    return rc;
}

int
main(int argc, char **argv)
{
    CLIBCRT     *crt    = __crtget();   /* A(CLIBCRT)               */
    CLIBGRT     *grt    = __grtget();   /* A(CLIBGRT)               */
    HTTPD       *httpd  = 0;
#if 0
    unsigned    *psa    = (unsigned *)0;
    unsigned    *tcb    = (unsigned *)psa[0x21C/4]; /* A(TCB) from PSATOLD  */
    unsigned    *asxb   = (unsigned *)ascb[0x6C/4]; /* A(ASXB) from ASCBASXB*/
    unsigned    *acee   = (unsigned *)asxb[0xC8/4]; /* A(ACEE) from ASXBSENV*/
#endif
    COM         *com    = __gtcom();
    CIB         *cib;
    int         i;
    int         rc;
    int         apf_at_entry;   /* authorized before auth_setup()? (#197) */
    unsigned    count;
    unsigned    *ecblist[10];
    HTTPD       server;
    char        vers[24];           /* MBT_VERSION, upper case: 000I/001I */

    grt->grtapp1    = &server;
    httpd           = grt->grtapp1;

    /* Zero the block HERE, not in initialize().  `server` is automatic storage
       and starts as whatever was on the stack, and two things read it before
       initialize() runs or without initialize() running at all: stc_identity()
       stores the retained ACEE into it, and the early `goto quit` paths below
       reach stc_identity_restore(), which tests that same field.  With the
       memset still down in initialize() those paths would act on garbage
       (#197). */
    memset(httpd, 0, sizeof(HTTPD));

    /* Which route authorizes the STC decides whether its own module storage is
    ** writable, and the log did not say until #197 sent someone looking.
    **
    ** MEASURE it with TESTAUTH -- do not infer it from crtopts below.
    ** `crtopts` is declared in libc370's clibcrt.h and read in @@apfset.c, but
    ** NOTHING IN LIBC370 EVER ASSIGNS IT: the CRT is zeroed, so CRTOPTS_AUTH
    ** is permanently clear.  A message built on it reports "BY SVC" on a
    ** module that was demonstrably fetched key 0, which is exactly what the
    ** first HTTPD002I said on mvsdev.  __isauth() is one TESTAUTH, no
    ** supervisor state, and it is what UFSD007I / FTPD008I already use.
    **
    ** It has to run BEFORE the setup below: after __autask() every task is
    ** authorized and the distinction is gone. */
    apf_at_entry = __isauth();

    /* Deliberately still on crtopts, dead field and all.  Because it is
    ** permanently clear this always takes unauth_setup(), the path that calls
    ** __autask() AND identify_cthread() -- and CTHREAD must be IDENTIFYed or
    ** `ATTACH EP=CTHREAD` (libc370 @@ctcrtx.c) finds nothing, since CTHREAD is
    ** an ENTRY inside this load module and not a library member.  auth_setup()
    ** is an empty stub, so "correcting" this test to __isauth() would, on a
    ** system that authorizes by library, skip the IDENTIFY and leave the
    ** server unable to create a single thread.  The dead field is what has
    ** been protecting httpd, ufsd and ftpd all along; see libc370#122 before
    ** touching either half. */
    if (crt->crtopts & CRTOPTS_AUTH) {
        /* this task was previously authorized */
        rc = auth_setup(argv[0]);
    }
    else {
        /* this task has not been authorized yet */
        rc = unauth_setup(argv[0]);
    }
    /* Startup banner, AFTER the APF setup above and deliberately so: an
    ** unauthorized WTO is prefixed '+' by the system, and the first two lines
    ** an operator reads should not be decorated with a diagnostic about a
    ** state that is about to change anyway.  It is still before the `rc`
    ** check, so a build that FAILS to authorize is identified in the log too
    ** -- with the '+', which at that point is the truth.
    **
    ** Which HTTPD, built from which source, against which C runtime: a
    ** deploy/relink mismatch (sysroot says X, the STC runs Y) then cannot
    ** hide, and a build carrying uncommitted changes says so instead of
    ** passing itself off as the commit it was branched from.  The buffers are
    ** scoped: they are dead the moment the banner is out. */
    /* Startup banner.  Which HTTPD, built from which source, against which C
    ** runtime.  A deploy/relink mismatch (sysroot says X, the STC runs Y) then
    ** cannot hide, and a build carrying uncommitted changes says so instead of
    ** passing itself off as the commit it was branched from.
    **
    ** If these lines have a leading '+' then we are not APF authorized yet --
    ** which is why the banner comes before auth_setup() and not after.  The
    ** buffers are scoped: they are dead the moment the banner is out. */
    http_upcase(vers, sizeof(vers), MBT_VERSION);
    {
        char commit[24];
        char stamp[48];

        wtof(MSG_STARTING,
             vers, http_upcase(commit, sizeof(commit), MBT_COMMIT));
        wtof(MSG_LIBC_VERSION,
             http_upcase(stamp, sizeof(stamp), libc370_version()));
#if MBT_COMMIT_DIRTY
        wtof(MSG_BUILD_DIRTY);
#endif
        /* The key is inferred from the route, not measured: an authorized job
        ** step has its module fetched key 0, an unauthorized one key 8, and
        ** SVC 244 arrives too late to change either.  It belongs next to the
        ** version banner because it is the other half of "which HTTPD is this"
        ** -- the same load module behaves differently depending on how it got
        ** authorized, and #197 was hard to place precisely because nothing
        ** said which route this STC had taken.
        **
        ** Silent when the setup FAILED: HTTPD012E has already said so, and
        ** naming a route there would claim an authorization the task does not
        ** hold.  FTPD008I suppresses it the same way; UFSD007I does not need
        ** to, because ufsd gives up before its banner. */
        if (!rc) {
            if (apf_at_entry)
                wtof(MSG_APF_BY_LIB);
            else
                wtof(MSG_APF_BY_SVC);
        }
    }

    if (rc) goto quit;

#if 0
    for(i=0;i<argc;i++) {
        wtof("arg#%d=\"%s\"", i, argv[i] ? argv[i] : "(null)");
    }
#endif

#if 0
    wtof("main ASCB(%08X) ASXB(%08X) ASXBSENV(%08X)", ascb, asxb, acee);
    if (acee) {
        wtof("ACEEACEE=%-4.4s", acee);
    }
#endif

    if (!com) {
        wtof(MSG_CONSOLE_FAILED);
        goto quit;
    }

#if 0
    /* If this is ever re-enabled: try() returns the ABEND code, which is not
       the same thing as initialize()'s return value (#226) -- one of them has
       to go somewhere else, or a config refusal and an abend become one
       number again. */
    rc = try(initialize,argc,argv);
    if (rc) {
        /* report abend and exit */
        rc = report_abend((unsigned)rc);
        goto cleanup;
    }
#else
    /* Note: All the heavy lifting occurs in the threads created by initialize().
       rc is the step return code from here on: 0 unless the server refused to
       start, and nothing below writes it, so a normal P HTTPD still ends
       CC 0000 (#226). */
    rc = initialize(argc,argv);
#endif

    if (!httpd->listen) {
        /* no listener socket, exit -- rc says whether that was a refusal */
        goto cleanup;
    }

#if 0
    /* issue "maxrates" command to the hercules console */
    httpcmd("maxrates", buf, sizeof(buf));
    wtof("%s", buf);
#endif

    /* set number of modify commands we'll queue */
    __cibset(5);

    httpd->flag |= HTTPD_FLAG_READY;
    /* The docroot is a UFS path and keeps its case; without one there is
       nothing to serve statically and saying "SERVING" would be a lie. */
    if (httpd->docroot[0])
        wtof(MSG_READY, vers, httpd->docroot);
    else
        wtof(MSG_READY_NODOC, vers);

    /* Note: The main thread (this thread) waits for console messages
     * like modify "/F jobname,..." and stop "/P jobname".
     *
     * The socket_thread() waits for client connections and
     * gives those clients to the thread manager for processing
     * by one of the worker_thread.
     */

    /* wait for a console command and process as needed */
    for(;;) {
        /* check for console command */
        if (*(com->comecbpt) & 0x40000000) {
            cib = __cibget();
            if (cib) {
                /* process console command */
                i = http_console(cib);
                __cibdel(cib);
                if (i) break;	/* must be a stop "/P jobname" */
            }
        }

        memset(ecblist, 0, sizeof(ecblist));
        count = build_ecblist(com, ecblist);
        if (count) {
            __asm__("WAIT ECBLIST=(%0)" : : "r"(ecblist));
        }
        else {
            /* we need to wait 1 second */
            __asm__("STIMER WAIT,BINTVL==F'100'   1 seconds");
        }
    }

cleanup:
    httpd->flag |= HTTPD_FLAG_QUIESCE;
    wtof(MSG_SHUTTING_DOWN);

    i = try(terminate,0);
    if (i) wtof(MSG_TERM_FAILED, i);

quit:
    /* Back to the account that took the authorization out, before giving it
       back -- see stc_identity_restore().  A no-op if the switch never ran, so
       the early-failure paths that reach this label are unaffected. */
    stc_identity_restore(httpd);

    if (crt) {
        if (crt->crtauth & CRTAUTH_STEPLIB) {
            __uastep();    /* reset STEPLIB APF authorization  */
        }
        if (crt->crtauth & CRTAUTH_ON) {
            __uatask();    /* reset APF authorization  */
        }
    }

    return rc;
}

#if 0
__asm__("IKJTCB LIST=YES");
__asm__("IHAASCB");
__asm__("IHAASXB");
__asm__("CSECT ,");
#endif
