/* HTTPD.C
** HTTP Server
*/
/* Build stamp.  Generated by mbt at every build: MBT_VERSION from the project
** version, MBT_COMMIT from `git rev-parse --short HEAD` (with "-dirty"
** appended when a TRACKED file differs from HEAD, and "unknown" outside a git
** checkout), MBT_COMMIT_DIRTY as the matching 0/1 flag.  Included here rather
** than in httpd.h so a new commit restamps the banner without rebuilding every
** object (mbt#59). */
#include <buildstamp.h>

#include "httpd.h"
#include "httpdmsg.h"               /* operator message catalog         */
#include "clibgrt.h"
#include "clibsock.h"
#include "clibver.h"                /* libc370_version()                */
#include "clibauth.h"               /* __autask/__austep/__uatask/__uastep */

static int socket_thread(void *arg1, void *arg2);
static int worker_thread(void *udata, CTHDWORK *work);

unsigned __stklen = 64*1024;

int main(int argc, char **argv);

#if 0
static void
close_stale_port(int port)
{
	int					rc;
	int					i;
    int                 addrlen;
    struct sockaddr     addr;
    struct sockaddr_in  serv_addr;

	for(i = 1; i < FD_SETSIZE; i++) {
		addrlen = sizeof(addr);
		rc = getsockname(i, &addr, &addrlen);
		if (rc==0) {
			struct sockaddr_in *in = (struct sockaddr_in*)&addr;
			if (in->sin_port == port) {
				wtof(MSG_STALE_SOCKET, i, in->sin_port);
				closesocket(i);
				sleep(2);	/* give the underlying host a chance to cleanup the socket */
				break;
			}
		}
	}
}
#endif

/* The security environment the STC started under -- the STC/STCGROUP account
** RAKF hands out.  Retained by stc_identity() rather than released, so that
** shutdown can put it back before it gives APF authorization up.  NULL until
** the switch succeeds, which is what makes the restore a no-op on every path
** that never got that far. */
static ACEE *stc_prev_acee = NULL;

/* Replace the default STC security environment with a dedicated, low
** privilege identity.  Called once, from initialize(), before anything opens
** a data set.  See the block comment at the call site for why this exists.
**
** The new ACEE is deliberately not freed: it becomes the address space's
** resting identity for the life of the server, and RTM releases it with the
** address space. */
static void
stc_identity(const char *user, const char *group)
{
	unsigned char	savekey;
	ACEE			*old_acee;
	ACEE			*new_acee;
	int				racf_rc	= 0;

	if (__super(PSWKEY0, &savekey)) {
		wtof(MSG_STCID_NOKEY);
		return;
	}

	/* The inherited environment is RETAINED, not released.
	**
	** Releasing it would be tidier but breaks shutdown.  HTTPD uses SVC 244 to
	** acquire APF authorization at start and to release it at end (__uatask()).
	** The acquire runs before this function -- RACINIT needs key 0, which needs
	** APF, so that order is forced -- and is covered by the STC account.  The
	** release at P HTTPD would run as the new identity, which has no
	** FACILITY SVC244 profile, and RAKF logs RAKF0005/RAKF000A on every single
	** stop.  stc_identity_restore() puts this ACEE back first, so the SVC 244
	** at the end runs under the same account that took the authorization out.
	**
	** Order also matters within this function, and the obvious order is wrong.
	** Releasing the inherited environment FIRST would leave nothing to fall
	** back on when the logon fails: racf_logout() does not merely free the
	** block, it __cas()es ASXBSENV to zero when the field still points at what
	** it deleted (libc370 raclgout.c does it by hand because RAKF leaves the
	** dead pointer).  A failed logon would then leave the address space with NO
	** resting identity at all -- not what HTTPD004W promises, and worse than the
	** privileged identity #177 set out to replace.  So: log on, then install. */
	old_acee = racf_get_acee();

	new_acee = racf_login(user, NULL, group, &racf_rc);
	if (new_acee) {
		racf_set_acee(new_acee);
		stc_prev_acee = old_acee;       /* for stc_identity_restore() */
		wtof(MSG_STCID_SET, user, group);
	}
	else {
		wtof(MSG_STCID_FAILED, user, group, racf_rc);
	}

	__prob(savekey, NULL);
}

/* Put the STC account back, immediately before APF authorization is released.
**
** __uatask() issues SVC 244, which RAKF gates on FACILITY SVC244.  The task
** took the authorization out under the STC account and must give it back under
** the same one, or every P HTTPD ends with RAKF0005/RAKF000A -- harmless, since
** the address space is ending anyway, but a permission failure logged on the
** healthy path teaches operators to ignore RAKF messages.
**
** Note this deliberately overwrites whatever ASXBSENV happens to hold, which by
** shutdown is often a CLIENT's ACEE rather than HTTPD/USER (measured: RAKF's
** RACINIT ENVIR=CREATE appears to plant the ACEE it creates, so every logon
** displaces the server identity -- see issue #176).  Restoring unconditionally
** is right precisely because the field cannot be trusted to still hold ours.
**
** racf_set_acee() does its own supervisor/key switching, so no __super() here.
** It does need APF, which is why this runs BEFORE the release, not after. */
static void
stc_identity_restore(void)
{
	if (!stc_prev_acee) return;

	racf_set_acee(stc_prev_acee);
	stc_prev_acee = NULL;
}

static void
initialize(int argc, char **argv)
{
    CLIBGRT             *grt        = __grtget();
    CLIBPPA             *ppa        = __ppaget();
    HTTPD               *httpd      = grt->grtapp1;
    unsigned            *psa        = (unsigned *)0;
    unsigned            *ascb       = (unsigned *)psa[0x224/4]; /* PSAAOLD  */
    unsigned            asid        = ((ascb[0x24/4]) >> 16);   /* ASCBASID */
    int                 rc;
    int					i;
    CTHDTASK            *task;
    const char 			*config		= NULL;
    const char			*stcuser	= HTTPD_STC_USER;
    const char			*stcgroup	= HTTPD_STC_GROUP;

    /* if something goes all wrong, capture it! */
    abendrpt(ESTAE_CREATE, DUMP_DEFAULT);

	/* look for "CONFIG=", "STCUSER=" and "STCGROUP=" parms.
	**
	** The identity keywords are read from the JCL PARM rather than from the
	** Parmlib on purpose: the logon below has to happen BEFORE http_config(),
	** which opens the Parmlib member and initializes UFS, and those are
	** exactly the file accesses that should no longer run under STC/STCGROUP.
	** Reading them from the member being opened would be circular. */
	for(i=0; i < argc; i++) {
		if (memcmp(argv[i], "CONFIG=", 7)==0) {
			config = &argv[i][7];
			while(*config=='=' || isspace((unsigned char)*config)) config++;
			if (!*config) config = "CONFIG";
		}
		else if (memcmp(argv[i], "STCUSER=", 8)==0) {
			stcuser = &argv[i][8];
			while(*stcuser=='=' || isspace((unsigned char)*stcuser)) stcuser++;
			if (!*stcuser) stcuser = HTTPD_STC_USER;
		}
		else if (memcmp(argv[i], "STCGROUP=", 9)==0) {
			stcgroup = &argv[i][9];
			while(*stcgroup=='=' || isspace((unsigned char)*stcgroup)) stcgroup++;
			if (!*stcgroup) stcgroup = HTTPD_STC_GROUP;
		}
	}

	/* STC identity switch: RACINIT ENVIR=CREATE for the configured userid.
	**
	** RAKF has no started-procedures table: its RACINIT path uses the started
	** procedure name only to decide THAT the caller is an STC, never WHICH
	** one, and assigns one hardcoded account -- STC/STCGROUP.  On a stock RAKF
	** profile set STCGROUP holds ALTER on every data set on the system, so the
	** server's resting identity, the one every RACF decision falls back to when
	** the caller passes no ACEE, is the most privileged one there is.  Any CGI
	** that does not establish an ACEE of its own inherits it (issue #177).
	**
	** racf_login() with pass == NULL bypasses password checking, so nothing has
	** to be stored anywhere; the STC is already APF authorized by this point.
	**
	** A failure warns and continues rather than refusing to start: #177 left
	** the policy open, and refusing turns a profile typo into an outage, while
	** continuing only leaves the identity where it already was.  Both paths say
	** so loudly -- what must not happen is a silent fallback. */
	stc_identity(stcuser, stcgroup);

    /* initialize our server data area */
    memset(httpd, 0, sizeof(HTTPD));
    strcpy(httpd->eye, HTTPD_EYE);
    httpd->flag |= HTTPD_FLAG_INIT;
    sprintf(httpd->rname, "HTTPD.%04X", asid);

    /* lock the httpd while we're making changes and creating threads */
    lock(httpd,0);

    /* httpd <--> httpx */
    httpd->httpx = httpx;
    
    /* set the server up time */
    httpd->uptime = time64(NULL);

    /* Server version.  MBT_VERSION rather than a -DVERSION on the command
       line: as a header it is a real prerequisite via -MMD, so a version or
       commit change recompiles this TU instead of leaving it stamped with the
       previous value.  Kept in its original case -- it is a value, and the
       WTO paths upper case their own copy (httpdmsg.h rule 3). */
    httpd->version	= MBT_VERSION;

	/* Get configuration from member/dataset/NULL */
	rc = http_config(httpd, config);
	if (rc) {
		/* The member is named by HTTPD022I above, and the specific failure by
		   the message right before this one -- printing the CONFIG= parm here
		   only ever produced "(null)", since it is not what gets read (#166). */
		wtof(MSG_CFG_ERRORS);
		if (httpd->listen) {
			closesocket(httpd->listen);
			httpd->listen = 0;
		}
		goto quit;
	}

	/* SMF configured but inactive is worth a line unasked: records are being
	** produced for a writer that is not there.  The healthy case is not --
	** it is one of the values F HTTPD,D CONFIG reports on demand (#184). */
	if (httpd->smf_level > SMF_LEVEL_NONE && !smf_active()) {
		wtof(MSG_SMF_INACTIVE, (int)httpd->smf_type);
	}

    /* create socket thread */
    httpd->socket_thread = cthread_create_ex(socket_thread,
        httpd, httpx, 32*1024);
    if (!httpd->socket_thread) {
        wtof(MSG_NO_SOCKET_THREAD);
        closesocket(httpd->listen);
        httpd->listen = 0;
        goto quit;
    }

    httpd->flag |= HTTPD_FLAG_LISTENER;

    /* update the main() thread information */
    task = cthread_self();
    if (task) {
        httpd->self = task;
        task->func = main;
        task->arg1 = (void*)argc;
        task->arg2 = argv;
        task->stacksize = ppa->ppastkln;
    }

	/* check configuration max and min task values */
    if (!(httpd->cfg_maxtask)) httpd->cfg_maxtask = 9;
    if (!(httpd->cfg_mintask)) httpd->cfg_mintask = 3;
    if (httpd->cfg_mintask > httpd->cfg_maxtask) {
		httpd->cfg_maxtask = httpd->cfg_mintask;
	}

    /* create 1 dispatcher and max 9 worker threads (576K total storage stack) */
    /* Note: the thread manager will only start 3 threads initially */
    httpd->mgr = cthread_manager_init(httpd->cfg_maxtask, worker_thread, httpd, 64*1024);
    if (!httpd->mgr) {
        /* gripe and continue */
        wtof(MSG_NO_WORKERS);
    }

	/* set the min task for the thread manager */
    if (httpd->mgr) {
		CTHDMGR *mgr = httpd->mgr;

        lock(mgr,1);

		mgr->mintask = httpd->cfg_mintask;
		if (httpd->cfg_mintask > mgr->maxtask) mgr->maxtask = httpd->cfg_mintask;

		/* wake up the thread manager thread */
		rc = cthread_post(&mgr->wait, CTHDMGR_POST_DATA);

        unlock(mgr,1);
    }
    
    /* Initialize CGI context pointers array */
    i = (httpd->cfg_cgictx + 1) * sizeof(void *);
    httpd->cgictx = (void **) calloc(1, (size_t)i);

quit:
	/* initialize our credential key */
	rc = cred_init(httpd, sizeof(HTTPD));
	if (rc) {
		wtof(MSG_CREDKEY_FAILED, rc);
	}

	/* Cache the blowfish key pointer in the HTTPD block so CGI-context code
	   (http_get_password) can reach it without credkey()/__wsaget(), which
	   only read the key from httpd's own GRT.  cred_init() runs here in that
	   GRT, so credkey() is valid; the key bytes live at a stable WSA address
	   readable across the shared address space, so caching the pointer (no
	   copy) is enough for a CGI running under its own GRT (issue #111). */
	httpd->credkey = credkey();

	/* Likewise cache the credential array pointer so http_logout() can reach
	   httpd's real store from a CGI's GRT.  cred_array() is GRT-relative too,
	   so a CGI calling it sees an empty/foreign array and logout invalidates
	   nothing; caching httpd's array pointer here (in httpd's GRT) fixes it
	   (issue #113, same class as #111). */
	httpd->credarr = cred_array();

    /* unlock the httpd */
    unlock(httpd,0);

    /* remove ESTAE */
    abendrpt(ESTAE_DELETE, DUMP_DEFAULT);

    http_exit("initialize()\n");
    return;
}

#if 0
static int
report_abend(unsigned abcode)
{
    int     rc;

    http_enter("report_abend()\n");

    abcode = (unsigned) rc;
    if (abcode > 4095) {
        /* system abend */
        wtof(MSG_ABEND_S, abcode >> 12);
        rc = 12;
    }
    else {
        /* user abend */
        wtof(MSG_ABEND_U, abcode);
        rc = 12;
    }

    http_exit("report_abend()\n");
    return rc;
}
#endif // 0

static void
close_fd_set(void)
{
    CLIBGRT *grt    = __grtget();

    http_enter("close_fd_set()\n");
    if (grt->grtsock) {
        unsigned count  = array_count(&grt->grtsock);
        while(count > 0) {
            count--;
            CLIBSOCK *s = grt->grtsock[count];
            if (!s) continue;
            if (s->socket >= 0) {
                closesocket(s->socket);
            }
        }
    }
    http_exit("close_fd_set()\n");
}

static void
terminate(void)
{
    CLIBGRT *grt        = __grtget();
    HTTPD   *httpd      = grt->grtapp1;
    HTTPC   *httpc;
    int     i;
    unsigned count;
    unsigned n;

    http_enter("terminate()\n");

    httpd->flag |= HTTPD_FLAG_QUIESCE;
    httpd->flag |= HTTPD_FLAG_SHUTDOWN;

    if (httpd->socket_thread) {
        CTHDTASK *task = httpd->socket_thread;

        for(i=0; (i < 10) && (!(task->termecb & 0x40000000)); i++) {
            if (i) {
                wtof(MSG_WAIT_SOCKET_THREAD, i);
            }
            /* we need to wait 1 second */
            __asm__("STIMER WAIT,BINTVL==F'100'   1 seconds");
        }

        if(!(task->termecb & 0x40000000)) {
            wtof(MSG_FORCE_DETACH);
        }
        cthread_delete(&httpd->socket_thread);
    }

    /* close the listener socket */
    if (httpd->listen > 0) {
        http_dbgf("closing socket(%d)\n", httpd->listen);
        closesocket(httpd->listen);
        httpd->listen = 0;
    }

    /* terminate the worker threads */
    cthread_manager_term(&httpd->mgr);

    if (httpd->httpc) {
        for(httpc=httpd->httpc[0]; httpc; httpc=httpd->httpc[0]) {
            http_dbgf("closing socket(%d)\n", httpc->socket);
            http_close(httpc);
        }
        array_free(&httpd->httpc);
    }

    /* cleanup the CGI array */
    if (httpd->httpcgi) {
        count = array_count(&httpd->httpcgi);

        for(n=0; n < count; n++) {
            HTTPCGI *cgi = httpd->httpcgi[n];
			if (!cgi) continue;
			if (cgi->pgm) 	free(cgi->pgm);
			if (cgi->path) 	free(cgi->path); 
            free(cgi);
        }

        array_free(&httpd->httpcgi);
    }

    /* free the per-CGI context pointer array (M11); the blocks it points to
       are AS-lifetime __getm storage by design and are not freed here */
    if (httpd->cgictx) {
        free(httpd->cgictx);
        httpd->cgictx = NULL;
    }

    /* httpd->ufs removed — per-client sessions freed in httpclos.c */

    if (httpd->ufssys) {
        ufs_sys_term(&httpd->ufssys);
        httpd->ufssys = NULL;
    }

	wtof(MSG_STATS,
		httpd->total_requests, httpd->total_errors,
		httpd->total_bytes_sent);

    /* just in case we missed something */
    close_fd_set();

    wtof(MSG_SHUTDOWN_DONE);

    http_exit("terminate()\n");
}

static int
build_fd_set(fd_set *read, fd_set *write, fd_set *excp)
{
    CLIBGRT     *grt    = __grtget();
    HTTPD       *httpd  = grt->grtapp1;
    int         maxsock = 0;
    unsigned    count   = array_count(&httpd->httpc);
    unsigned    n;
    HTTPC       *httpc;
#if 0
    http_enter("build_fd_set()\n");
#endif
    if (read && httpd->listen >= 0) {
        memset(read, 0, sizeof(fd_set));
        FD_SET(httpd->listen, read);
        if (httpd->listen > maxsock) maxsock = httpd->listen;
    }
    if (write) {
        memset(write, 0, sizeof(fd_set));
    }
    if (excp) {
        memset(excp, 0, sizeof(fd_set));
    }

    /* NOTE: httpd->httpc[] is read here without lock.
     * This is safe because build_fd_set() runs in the same
     * socket_thread as array_add(). array_del() in httpclos
     * runs in worker threads but sets entries to NULL before
     * removal, and we check for NULL below.
     */
    for(n=0; n < count; n++) {
        httpc = httpd->httpc[n];
        if (!httpc) continue;           /* no client handle? */

        if (httpc->socket < 0) continue;   /* no socket? */

        if (httpc->socket > maxsock) maxsock = httpc->socket;
        if (read)   FD_SET(httpc->socket, read);
        if (write)  FD_SET(httpc->socket, write);
        if (excp)   FD_SET(httpc->socket, excp);
    }

    if (maxsock) maxsock++;
#if 0
    http_exit("build_fd_set(), maxsock=%d\n", maxsock);
#endif
    return maxsock;
}

static int
process_clients(fd_set *read, fd_set *write, fd_set *excp)
{
    CLIBGRT     *grt    = __grtget();
    HTTPD       *httpd  = grt->grtapp1;
    int         rc      = http_process_clients();
    int         lockrc;
    unsigned    count;
    unsigned    n;
    HTTPC       *httpc;

    /* process all the http clients (does its own locking) */
    rc = http_process_clients();

    /* get lock so we can cleanup any clients that are closing */
    lockrc = lock(httpd, 0);
    if (lockrc==0) goto httpd_locked;   /* we have the lock */
    if (lockrc==8) goto httpd_locked;   /* we already had the lock */
    wtof(MSG_LOCK_FAILED, __func__);
    goto quit;

httpd_locked:
    /* look for any clients that need to be closed */
    count = array_count(&httpd->httpc);
    for(n=0; n < count; n++) {
        httpc = httpd->httpc[n];
        if (!httpc) continue;           /* no client handle? */

        if (httpc->state==CSTATE_CLOSE) {
            /* we close a single client at a time,
            ** other clients will be closed on next pass.
            */
            http_dbgf("closing client(%u) socket(%d)\n",
                n+1, httpc->socket);
            http_close(httpc);
            break;
        }
    }
    if (lockrc==0) unlock(httpd, 0);

quit:
    return 0;
}

/* NOTE: an earlier version of this probe bisected with malloc() to report the
   largest obtainable block.  It abended the socket thread S878 on its second
   run -- libc370's malloc goes to @@GETM, which issues GETMAIN **RU**
   (unconditional): under storage pressure it abends instead of returning
   NULL.  That is the defect this debugging found, so the probe must never
   allocate; it only reports counts. */

static int
socket_thread(void *arg1, void *arg2)
{
    CLIBGRT     *grt    = __grtget();
    HTTPD       *httpd  = grt->grtapp1;
    unsigned    *psa    = (unsigned *)0;
    unsigned    *tcb    = (unsigned *)psa[0x21C/4]; /* A(TCB) from PSATOLD  */
    CTHDTASK    *task   = cthread_self();
    CTHDMGR     *mgr    = httpd->mgr;
    int         rc;
    int         sock;
    int         len;
    HTTPC       *httpc;
    timeval     wait;
    int         maxsock;
    unsigned    count;
    fd_set      read;
    struct sockaddr_in addr;
    struct sockaddr_in *a = (struct sockaddr_in *)&addr;
    time64_t    last_sweep = time64(NULL);  /* credential reaper throttle (M2) */

    http_enter("socket_thread()\n");

    wtof(MSG_THREAD_START, "SOCKET THREAD", tcb, task, task->stacksize);

    /* if something goes all wrong, capture it! */
    abendrpt(ESTAE_CREATE, DUMP_DEFAULT);

    /* we loop until we're shut down */
    while(task) {
        if (httpd->flag & HTTPD_FLAG_SHUTDOWN) break;

        /* periodically reap idle credentials (M2), throttled to ~60s so the
           select loop's ~1/s wakeups don't sweep every tick */
        {
            time64_t now = time64(NULL);
            if (difftime64(now, last_sweep) >= 60.0) {
                last_sweep = now;
                if (httpd->cfg_session_timeout)
                    cred_reap((unsigned)httpd->cfg_session_timeout * 60);

            }
        }

        /* process clients */
        if (process_clients(&read, NULL, NULL)) break;

        /* build fd_set for select() */
        maxsock = build_fd_set(&read, NULL, NULL);
        if (!maxsock) {
            wtof(MSG_MAXSOCK_ZERO);
            goto quit;
        }

        /* set the wait interval */
        wait.tv_sec     = 0;
        wait.tv_usec    = 0;

        mgr = httpd->mgr;
        if (mgr) {
            /* we're using worker threads for client processing */
            wait.tv_sec = 1;

            /* if we're quiesced then break out of loop */
            if (httpd->flag & HTTPD_FLAG_QUIESCE) break;
        }
        else {
            /* we're doing client processing from this thread */
            count       = array_count(&httpd->httpc);

            if (count==0) {
                /* no clients, so wait just a little bit */
                wait.tv_sec = 1;

                /* if we're quiesced then break out of loop */
                if (httpd->flag & HTTPD_FLAG_QUIESCE) break;
            }
        }

        /* wait for something to do */
        rc = selectex(maxsock, &read, NULL, NULL, &wait, NULL);
        if (rc<0) {
            if (httpd->flag & HTTPD_FLAG_QUIESCE) continue;     /* checked at top of loop */
            if (httpd->flag & HTTPD_FLAG_SHUTDOWN) continue;    /* checked at top of loop */
            wtof(MSG_SELECT_FAILED, rc, errno);
            goto quit;
        }

        /* if we're quiesced then don't accept new connections */
        if (httpd->flag & HTTPD_FLAG_QUIESCE) continue;

        /* first check for new connections */
        if (FD_ISSET(httpd->listen, &read)) {
            /* new client wants to connect */
            len = sizeof(addr);
            sock = accept(httpd->listen, &addr, &len);
            if (sock<0) {
                /* transient (client reset before accept, EINTR, ...): drop
                   this connection but keep listening.  A real shutdown/quiesce
                   is handled at the top of the loop, so don't kill the
                   listener on a single accept() failure. */
                if (httpd->flag & HTTPD_FLAG_QUIESCE) continue;
                if (httpd->flag & HTTPD_FLAG_SHUTDOWN) continue;
                wtof(MSG_ACCEPT_FAILED, sock, errno);
                http_dbgf("accept() failed, rc=%d, error=%d\n", sock, errno);
                continue;
            }

            http_dbgf("new connection on socket=%d\n", sock);

            len = 1;    /* set non-blocking I/O */
            if (ioctlsocket(sock, FIONBIO, &len)) {
                wtof(MSG_NONBLOCK_FAILED, sock);
                http_dbgf("Unable to set non-blocking I/O for socket %d\n",
                    sock);
            }

            /* we've accepted a connection */
            httpc = calloc(1, sizeof(HTTPC));
            if (!httpc) {
                /* out of memory for this client: close the accepted socket
                   (don't leak the fd) and keep listening -- memory may free
                   up; a persistent OOM still lets QUIESCE/SHUTDOWN exit. */
                wtof(MSG_OUT_OF_MEMORY);
                closesocket(sock);
                continue;
            }
            strcpy(httpc->eye, HTTPC_EYE);
            httpc->httpd  = httpd;
            httpc->socket = sock;
            httpc->addr   = a->sin_addr.s_addr;
            httpc->port   = a->sin_port;
            httpc->state  = CSTATE_IN;
            httpsecs(&httpc->start);
            httpd->active_connections++;

            // SMF session tracking
            {
                time_t now = time(0);
                struct tm *tm = localtime(&now);
                httpc->connect_time = (unsigned)(
                    tm->tm_hour * 360000L
                    + tm->tm_min * 6000L
                    + tm->tm_sec * 100L);
            }
            /* UFS session created lazily by http_get_ufs() */

            mgr = httpd->mgr;
            if (mgr) {
                /* we have a thread manager */
                if (mgr->state == CTHDMGR_STATE_QUIESCE ||
                    mgr->state == CTHDMGR_STATE_STOPPED) {
                    /* manager is not available */
                    http_close(httpc);
                }
                else {
                    /* queue client to thread manager work queue.  A calloc
                       OOM inside cthread_queue_add returns non-zero without
                       queueing -- close the client so its HTTPC + socket don't
                       leak.  (Success returns 0; a QUIESCE/STOPPED race also
                       returns 0 there, but is covered by the state check above
                       -- the narrow remaining window is benign, reclaimed at
                       address-space end.) */
                    if (cthread_queue_add(mgr, httpc)) {
                        http_close(httpc);
                    }
                }
            }
            else {
                /* add new client to array of clients */
                lock(httpd, 0);
                array_add(&httpd->httpc, httpc);
                unlock(httpd, 0);
            }
        } /* if (FD_ISSET(httpd->listen, &read)) */

    } /* while(task) */

quit:
	wtof(MSG_THREAD_STOP, "SOCKET THREAD", tcb, task, task->stacksize);

    abendrpt(ESTAE_DELETE, DUMP_DEFAULT);
    http_exit("socket_thread()\n");
    return 0;
}

/* Drive one client's state machine to completion (or to shutdown).  Split
   out so worker_thread can run it under try() (ESTAE): a core abend anywhere
   in the request pipeline then returns here for cleanup instead of
   percolating past http_close() -- which would otherwise leak the HTTPC, its
   socket, env and UFS handles and leave a stale pointer in httpd->busy (M1). */
static int
serve_client(HTTPC *httpc, CTHDWORK *work)
{
    /* DEBUG #217: this loop had no escape.  http_process_client() may return
       without advancing httpc->state (the busy-exit in httppc.c), and there is
       no wait anywhere in the loop, so the worker then spins on ENQ/DEQ
       forever and is lost to the pool.  Count passes that change nothing and
       break out, loudly, instead of taking the address space down. */
    int     spin    = 0;
    short   last    = httpc->state;

    while (httpc->state != CSTATE_CLOSE) {
        http_process_client(httpc);
        if (work->state == CTHDWORK_STATE_SHUTDOWN) break;

        if (httpc->state == last) {
            /* No progress.  In worker mode this client has exactly one owner
               -- this loop; it came off the work queue and nothing else
               processes it.  So if the no-progress pass was httppc()'s
               busy-exit, the httpd->busy entry is stale by definition (#159:
               left behind by an earlier failure on this worker, or by a freed
               client that occupied the same storage).  Clear it on the FIRST
               such pass and keep serving: the request proceeds normally and
               the wedge never forms.  If the client is NOT in busy, the stall
               has another cause (e.g. http_set_busy() failing on a full
               region) -- nothing to repair here, let the spin guard below end
               it.  The guard stays as the last resort either way. */
            if (spin == 0 && http_is_busy(httpc)) {
                wtof(MSG_STALE_BUSY,
                    httpc, (int)httpc->state, httpc->socket,
                    httpc->request_count);
                http_reset_busy(httpc);
            }
            if (++spin >= 1000) {
                wtof(MSG_SPIN,
                    httpc, (int)httpc->state, httpc->socket,
                    httpc->request_count, work);
                /* The spin means httppc() kept taking its busy-exit without
                   ever reaching http_reset_busy(), so this client is still in
                   httpd->busy -- and http_close() does not clear that array.
                   Drop the entry here, or the freed HTTPC address stays behind
                   and wedges the next client allocated at it. */
                http_reset_busy(httpc);
                httpc->state = CSTATE_CLOSE;
                break;
            }
        }
        else {
            spin = 0;
            last = httpc->state;
        }
    }
    return 0;
}

static int
worker_thread(void *udata, CTHDWORK *work)
{
    unsigned    *psa    = (unsigned *)0;
    unsigned    *tcb    = (unsigned *)psa[0x21C/4]; /* A(TCB) from PSATOLD  */
    CTHDTASK    *task   = cthread_self();
    int         rc      = 0;
    char        *data   = NULL;
    HTTPC       *httpc  = NULL;
    char        name[20];   /* "WORKER(xxxxxx)" for HTTPD060I/061I */

    http_enter("worker_thread()\n");

    /* if something goes all wrong, capture it! */
    abendrpt(ESTAE_CREATE, DUMP_DEFAULT);

    sprintf(name, "WORKER(%06X)", (unsigned)work);
    wtof(MSG_THREAD_START, name, tcb, task, task->stacksize);

    while(task) {
        if (work->state == CTHDWORK_STATE_SHUTDOWN) break;

        rc = cthread_worker_wait(work,&data);
        if (rc == CTHDWORK_POST_SHUTDOWN) break;

        if (rc == CTHDWORK_POST_REQUEST) {
            /* process request */
            httpc = (HTTPC*)data;
            if (httpc && strcmp(httpc->eye, HTTPC_EYE)==0) {
                /* Run the request under ESTAE.  A core abend (not a CGI under
                   __linkds, whose abends are caught there) would otherwise
                   skip http_close() and leak the client; try() catches it so
                   cleanup still runs.  On an abend the pipeline never reached
                   http_reset_busy() (httppc.c:149), so drop the stale busy
                   entry here -- while httpc is still valid, before close frees
                   it.  The normal path already cleared busy, so gate on rc. */
                rc = try(serve_client, httpc, work);
                if (rc) {
                    wtof(MSG_WORKER_ABEND,
                        rc, work, httpc, httpc->socket);
                    http_reset_busy(httpc);
                }
                http_dbgf("closing client(%08X) socket(%d)\n",
                    httpc, httpc->socket);
                http_close(httpc);
            }
            else {
                wtodumpf(data, 16, "%s unknown request", __func__);
            }
        }
        else if (rc == CTHDWORK_POST_TIMER) {
            /* process timer */
        }
    }

	wtof(MSG_THREAD_STOP, name, tcb, task, task->stacksize);

    abendrpt(ESTAE_DELETE, DUMP_DEFAULT);

    http_exit("worker_thread()\n");
    return 0;
}

static unsigned
build_ecblist(COM *com, unsigned **ecblist)
{
    unsigned        pos     = 0;
    unsigned        *ecbp;

    if (com->comecbpt) {
        ecblist[pos++] = com->comecbpt;
    }

    if (pos) {
        ecbp = ecblist[pos-1];
        ecblist[pos-1] = (unsigned*)((unsigned)ecbp | 0x80000000);
    }

    return pos;
}

#include "cde.h"
static CDE *
find_cde(const char *name)
{
    unsigned    *psa    = 0;                        /* low core == PSA      */
    unsigned    *tcb    = (unsigned*)psa[0x21c/4];  /* TCB      == PSATOLD  */
    unsigned    *jstcb  = (unsigned*)tcb[0x7c/4];   /* JSTCB    == TCBJSTCB */
    CDE         *cde    = (CDE*)jstcb[0x2c/4];      /* CDE      == TCBJPQ   */
    int         i;
    char        temp[9] = "        ";

    for(i=0; i < 8 && name[i]; i++) {
        temp[i] = name[i];
    }

    while(cde) {
        if (memcmp(cde->CDNAME, temp, 8)==0) {
            return cde;
            break;
        }
        cde = cde->CDCHAIN;
    }

    return NULL;
}

static int
auth_cde(CDE *cde)
{
    int     rc = 0;

    if (cde) {
        __asm__("MODESET KEY=ZERO,MODE=SUP\n" : : : "0", "1", "14", "15");
        cde->CDATTR2 |= (CDSYSLIB | CDAUTH);
        __asm__("MODESET KEY=NZERO,MODE=PROB" : : : "0", "1", "14", "15");
    }

    return rc;
}

static int
auth_name(const char *name)
{
    int     rc = 0;
    CDE     *cde = find_cde(name);

    if (cde) {
        /* wtodumpf(cde, sizeof(CDE), "%s %s CDE before auth_cde()", __func__, name); */
        rc = auth_cde(cde);
        /* wtodumpf(cde, sizeof(CDE), "%s %s CDE after auth_cde()", __func__, name); */
    }
    else {
        /* wtof("%s %s CDE was not found", __func__, name); */
        rc = 4;
    }

    return rc;
}

static int
identify_cthread(void)
{
    int     rc = 0;

    /* CTHREAD does not already exist, identify it now */
    /* wtof("%s preparing to IDENTIFY CTHREAD", __func__); */

    __asm__("L     1,=V(CTHREAD)    A(thread driver routine)\n\t"
            "LA    0,=CL8'CTHREAD'\n\t"
            "IDENTIFY EPLOC=(0),ENTRY=(1)\n\t"
            "ST    15,0(,%0)\n" : : "r" (&rc): "0", "1", "14", "15");
    __asm__("\n*\n");

    /* wtof("%s IDENTIFY CTHREAD rc=%d", __func__, rc); */

    rc = auth_name("CTHREAD");

    return rc;
}

static int auth_setup(const char *name)
{
    int     rc = 0;

    return rc;
}

static int unauth_setup(const char *name)
{
    int         rc      = 0;
    CLIBCRT     *crt    = __crtget();   /* A(CLIBCRT)               */

    /* this task is not currently APF authorized */
    rc = __autask();    /* APF authorize this task  */
    /* wtof("%s __autask() rc=%d", __func__, rc); */
    if (rc==0) {
        if (crt->crtauth & CRTAUTH_ON) {
            /* Silent on the healthy path (UFSD/FTPD do the same): that APF was
            ** obtained is only interesting when it FAILS, and HTTPD012E covers
            ** that. */
            /* we want the STEPLIB APF authorized as well */
            rc = __austep();    /* APF authorize the STEPLIB */
            if (rc==0) {
                if (crt->crtauth & CRTAUTH_STEPLIB) {
                    rc = auth_name(name);
                    /* wtof("%s auth_name(%s) rc=%d", __func__, name, rc); */
                    rc = identify_cthread();
                    /* wtof("%s identify_cthread() rc=%d", __func__, rc); */
                }
            }
        }
        else {
            rc = auth_name(name);
            /* wtof("%s auth_name(%s) rc=%d", __func__, name, rc); */
            rc = identify_cthread();
            /* wtof("%s identify_cthread() rc=%d", __func__, rc); */
        }
    }
    else {
        wtof(MSG_APF_FAILED, name);
    }

    return rc;
}

int
main(int argc, char **argv)
{
    CLIBCRT     *crt    = __crtget();   /* A(CLIBCRT)               */
    CLIBGRT     *grt    = __grtget();   /* A(CLIBGRT)               */
    HTTPD       *httpd  = 0;
#if 0
    unsigned    *psa    = (unsigned *)0;
    unsigned    *tcb    = (unsigned *)psa[0x21C/4]; /* A(TCB) from PSATOLD  */
    unsigned    *asxb   = (unsigned *)ascb[0x6C/4]; /* A(ASXB) from ASCBASXB*/
    unsigned    *acee   = (unsigned *)asxb[0xC8/4]; /* A(ACEE) from ASXBSENV*/
#endif
    COM         *com    = __gtcom();
    CIB         *cib;
    int         i;
    int         rc;
    unsigned    count;
    unsigned    *ecblist[10];
    HTTPD       server;
    char        vers[24];           /* MBT_VERSION, upper case: 000I/001I */

    grt->grtapp1    = &server;
    httpd           = grt->grtapp1;

    if (crt->crtopts & CRTOPTS_AUTH) {
        /* this task was previously authorized */
        rc = auth_setup(argv[0]);
    }
    else {
        /* this task has not been authorized yet */
        rc = unauth_setup(argv[0]);
    }
    /* Startup banner, AFTER the APF setup above and deliberately so: an
    ** unauthorized WTO is prefixed '+' by the system, and the first two lines
    ** an operator reads should not be decorated with a diagnostic about a
    ** state that is about to change anyway.  It is still before the `rc`
    ** check, so a build that FAILS to authorize is identified in the log too
    ** -- with the '+', which at that point is the truth.
    **
    ** Which HTTPD, built from which source, against which C runtime: a
    ** deploy/relink mismatch (sysroot says X, the STC runs Y) then cannot
    ** hide, and a build carrying uncommitted changes says so instead of
    ** passing itself off as the commit it was branched from.  The buffers are
    ** scoped: they are dead the moment the banner is out. */
    /* Startup banner.  Which HTTPD, built from which source, against which C
    ** runtime.  A deploy/relink mismatch (sysroot says X, the STC runs Y) then
    ** cannot hide, and a build carrying uncommitted changes says so instead of
    ** passing itself off as the commit it was branched from.
    **
    ** If these lines have a leading '+' then we are not APF authorized yet --
    ** which is why the banner comes before auth_setup() and not after.  The
    ** buffers are scoped: they are dead the moment the banner is out. */
    http_upcase(vers, sizeof(vers), MBT_VERSION);
    {
        char commit[24];
        char stamp[48];

        wtof(MSG_STARTING,
             vers, http_upcase(commit, sizeof(commit), MBT_COMMIT));
        wtof(MSG_LIBC_VERSION,
             http_upcase(stamp, sizeof(stamp), libc370_version()));
#if MBT_COMMIT_DIRTY
        wtof(MSG_BUILD_DIRTY);
#endif
    }

    if (rc) goto quit;

#if 0
    for(i=0;i<argc;i++) {
        wtof("arg#%d=\"%s\"", i, argv[i] ? argv[i] : "(null)");
    }
#endif

#if 0
    wtof("main ASCB(%08X) ASXB(%08X) ASXBSENV(%08X)", ascb, asxb, acee);
    if (acee) {
        wtof("ACEEACEE=%-4.4s", acee);
    }
#endif

    if (!com) {
        wtof(MSG_CONSOLE_FAILED);
        goto quit;
    }

#if 0
    rc = try(initialize,argc,argv);
    if (rc) {
        /* report abend and exit */
        rc = report_abend((unsigned)rc);
        goto cleanup;
    }
#else
    /* Note: All the heavy lifting occurs in the threads created by initialize() */
    initialize(argc,argv);
#endif

    if (!httpd->listen) {
        /* no listener socket, exit */
        goto cleanup;
    }

#if 0
    /* issue "maxrates" command to the hercules console */
    httpcmd("maxrates", buf, sizeof(buf));
    wtof("%s", buf);
#endif

    /* set number of modify commands we'll queue */
    __cibset(5);

    httpd->flag |= HTTPD_FLAG_READY;
    /* The docroot is a UFS path and keeps its case; without one there is
       nothing to serve statically and saying "SERVING" would be a lie. */
    if (httpd->docroot[0])
        wtof(MSG_READY, vers, httpd->docroot);
    else
        wtof(MSG_READY_NODOC, vers);

    /* Note: The main thread (this thread) waits for console messages
     * like modify "/F jobname,..." and stop "/P jobname".
     *
     * The socket_thread() waits for client connections and
     * gives those clients to the thread manager for processing
     * by one of the worker_thread.
     */

    /* wait for a console command and process as needed */
    for(;;) {
        /* check for console command */
        if (*(com->comecbpt) & 0x40000000) {
            cib = __cibget();
            if (cib) {
                /* process console command */
                i = http_console(cib);
                __cibdel(cib);
                if (i) break;	/* must be a stop "/P jobname" */
            }
        }

        memset(ecblist, 0, sizeof(ecblist));
        count = build_ecblist(com, ecblist);
        if (count) {
            __asm__("WAIT ECBLIST=(%0)" : : "r"(ecblist));
        }
        else {
            /* we need to wait 1 second */
            __asm__("STIMER WAIT,BINTVL==F'100'   1 seconds");
        }
    }

cleanup:
    httpd->flag |= HTTPD_FLAG_QUIESCE;
    wtof(MSG_SHUTTING_DOWN);

    i = try(terminate,0);
    if (i) wtof(MSG_TERM_FAILED, i);

quit:
    /* Back to the account that took the authorization out, before giving it
       back -- see stc_identity_restore().  A no-op if the switch never ran, so
       the early-failure paths that reach this label are unaffected. */
    stc_identity_restore();

    if (crt) {
        if (crt->crtauth & CRTAUTH_STEPLIB) {
            __uastep();    /* reset STEPLIB APF authorization  */
        }
        if (crt->crtauth & CRTAUTH_ON) {
            __uatask();    /* reset APF authorization  */
        }
    }

    return rc;
}

#if 0
__asm__("IKJTCB LIST=YES");
__asm__("IHAASCB");
__asm__("IHAASXB");
__asm__("CSECT ,");
#endif
